- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/master"
  fail_on_prepare_env_warning: true
  actions:
  - action: "bash start"
    type: "NATIVE_BUILD_DOCKER_CLI"
    commands:
    - "sudo apt-get update && sudo apt-get upgrade -y"
    - "sudo apt-get install python3-pip ffmpeg -y"
    - "sudo pip3 install -U pip"
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash && source ~/.bashrc && nvm install v18"
    - "git clone https://github.com/budeg/bio-aviaxmusic && cd bio-aviaxmusic"
    - "pip3 install -U -r requirements.txt"
    - "cp sample.env .env"
    - "vi .env"
    - "sudo apt install tmux -y && tmux"
    - "bash start"
    instance_type: "GENERAL_MEDIUM"
